Display wallets currency
ScalaConsultants/Blockchain-Analytic-Dashboard pull request #141
Opened 2019-12-09 08:16 UTC by dariuszsobkowicz

2019-12-09 08:31 UTC, Milena-Wasiak requested changes

2019-12-09 08:31 UTC, Milena-Wasiak commented on src/components/DashboardTable/DashboardTable-container.tsx
> +//@ts-ignore
dodaj ostatnia pusta linie, a nie ts-ignore

2019-12-09 08:31 UTC, Milena-Wasiak commented on src/components/DashboardTable/DashboardTableHeader-container.tsx
> +        <div>HELLO</div>
???

2019-12-09 08:31 UTC, Milena-Wasiak commented on src/components/DashboardTable/DashboardTableHeader-container.tsx
> +    // setSwitchState(event.target.checked);
wywal komentarz :) juz nie bedzie potrzebne

2019-12-09 08:31 UTC, Milena-Wasiak commented on src/components/DashboardTable/DashboardTableHeader-container.tsx
>    const [switchState, setSwitchState] = React.useState(true);
i ta linia tez nie jest potrzebna bo jest zakomentowane jej uzycie

2019-12-09 08:31 UTC, Milena-Wasiak commented on src/components/DashboardTable/DashboardTableHeader-container.tsx
> +    console.log('change')
to tez nie jest potrzebne

2019-12-09 08:46 UTC, dariuszsobkowicz commented on src/components/DashboardTable/DashboardTableHeader-container.tsx
> +    console.log('change')
wiem wiem jeszcze będę robił cleanup ;)

2019-12-10 06:43 UTC, Milena-Wasiak approved these changes
👍

2019-12-10 06:53 UTC, merged