Bv 131 - Create wallets page
ScalaConsultants/Blockchain-Analytic-Dashboard pull request #85
Opened 2019-10-29 12:58 UTC by wojciech-nowakowski

2019-10-29 13:24 UTC, Milena-Wasiak requested changes
Sprawdź też błędy z esLinta
yarn eslint src/components/WalletList/**

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +const WalletsList = (props: any): React.ReactElement => {
postaraj sie otypowac props

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +        headerColumns.map((row: any) => (
postaraj sie otypowac :)

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +    const renderWalletsListRows = (walletsList: any[]) => {
postaraj sie otypowac :)

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +        )).map((row: any, index: number) => (
postaraj sie otypowac :)

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +                                // onScroll={(e: any) => handleScroll(e.target)}
wywal komentarz

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +                        {/* <Loader isLoading={walletsIsFetching} fullPage={false} /> */}
czemu loadera zakomentowales?

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +        setDescription(value);
usun {} i zawin do jednej linijki

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-styles.tsx
> +  },
nie uzywane style wywal

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/wallets.tsx
> +
nie potrzebna pusta linia

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-styles.tsx
> +  }, button: {
style button od nowej linijki

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-styles.tsx
> +  },unassignedColor: {
style unassignedColor od nowej linijki

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/EditWalletModal/EditWalletModal-view.tsx
> +      ><img src={`${PUBLIC_URL}/icons/wallet.png`} style={{ width: '13px', marginRight: '5px' }} />
dodaj atrybut alt

2019-10-29 13:24 UTC, Milena-Wasiak commented on src/components/SwitchButton/SwitchButton-styles.tsx
> +    color: 'radial-gradient(50% 1368.05% at 50% 48.72%, rgba(169, 176, 204, 0.5) 0%, rgba(116, 121, 140, 0.5) 100%)',
👍

2019-10-30 06:16 UTC, Milena-Wasiak approved these changes

2019-10-30 06:16 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +                    <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
a może row.id == 'watched' && classes.labelDisabled

czemu nie może być '==='?

2019-10-30 06:16 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +                <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
to samo co wyzej row.id == 'watched' && classes.labelDisabled

2019-10-30 07:01 UTC, dariuszsobkowicz commented on src/components/EditWalletModal/EditWalletModal-view.tsx
> +      ><img src={`${PUBLIC_URL}/icons/wallet.png`} style={{ width: '13px', marginRight: '5px' }} />
maybe use a class instead of style

2019-10-30 07:04 UTC, dariuszsobkowicz commented on src/components/SwitchButton/SwitchButton-styles.tsx
> +    width: '12px',
mixed quotation marks, please use single or double

2019-10-30 07:22 UTC, dariuszsobkowicz commented on src/components/WalletsList/WalletsList-container.tsx
> +                    <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
@Milena-Wasiak ale tutaj z tego co widzę ma zwracać string a `row.id == 'watched' && classes.labelDisabled` może być boolean ;)

2019-10-30 07:29 UTC, dariuszsobkowicz commented on src/components/WalletsList/WalletsList-container.tsx
> +            walletsList,
może być też użyte `return walletsList.length && (stableSort ..............`

2019-10-30 07:31 UTC, dariuszsobkowicz commented on src/components/WalletsList/WalletsList-container.tsx
> +                        <span className={row.market == Markets.UNASSIGNED ? classes.labelDisabled : ''}>{row.market}</span>
a może `clsx` zamiast class + ' ' + class

2019-10-30 07:33 UTC, dariuszsobkowicz commented on src/components/WalletsList/WalletsList-container.tsx
> +                <Grid item xs={1} style={{ marginRight: '20px', zIndex: 1000, cursor: 'pointer' }}>
czemu nie klasa tylko style?

2019-10-30 07:34 UTC, dariuszsobkowicz approved these changes

2019-10-30 08:22 UTC, wojciech-nowakowski commented on src/components/WalletsList/WalletsList-container.tsx
> +                <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
className musi miec zwrócony pusty string

2019-10-30 08:23 UTC, dariuszsobkowicz commented on src/components/WalletsList/WalletsList-container.tsx
> +                <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
@Milena-Wasiak 🤦‍♂️

2019-10-30 08:25 UTC, Milena-Wasiak commented on src/components/WalletsList/WalletsList-container.tsx
> +                <span className={row.id == 'watched' ? classes.labelDisabled : ''}>{row.label}</span>
🤕

2019-10-30 09:12 UTC, merged